remote_theme: "jekyll/minima@v2.5.2"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

email: mail@djmaxus.dev
# title: Max Elizarev
author: Max Elizarev

github_username: djmaxus
linkedin_username: djmaxus

header_pages:
  - about.md

mastodon:
  - username: djmaxus
    instance: https://www.buymeacoffee.com
