name: Page Preview
on:
    pull_request:
        branches: "master"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/configure-pages@v5
        - uses: actions/jekyll-build-pages@v1
        - uses: actions/upload-artifact@v3
          with:
            name: site
            path: ./_site
